### ISSUE TITLE
How to list only those entries owned by a certain user

### ISSUE THREAD

**Issue by robp2175** [kaltura/KalturaAPISampleListEntries#1]
Great script, I greatly appreciate it and hope you might help me with one piece. I need to be able to list only this entries by a single owner. If you could help me out I would greatly appreciate it.

**Comment by jessp01** [comment]
Hello,

$filter = new KalturaMediaEntryFilter();
You can filter by:
partnerIdEqual
partnerIdIn
userIdEqual
creatorIdEqual
userIdIn

Do this before calling:
$filteredListResult = $client->media->listAction($filter, $pager);

Let me know if you need further assistance,

**Comment by robp2175** [comment]
Could you give me an example of usage please?

Sent from my iPad

On Dec 25, 2014, at 4:53 AM, Jess Portnoy <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

$filter = new KalturaMediaEntryFilter();
You can filter by:
partnerIdEqual
partnerIdIn
userIdEqual
creatorIdEqual
userIdIn

Do this before calling:
$filteredListResult = $client->media->listAction($filter, $pager);

Let me know if you need further assistance,

##

**Comment by robp2175** [comment]
Thank you, this is working perfectly.
